---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: v1
data:
    LOKI_HOST: ENC[AES256_GCM,data:R3XR2h6/oHPMy7ZaA+A4gwLAM3ULobKwuol8ctlYDlVqbVpff1EZWh9x1oh6ovr2bP8Hpw==,iv:TwyBV1PggNZHhQMrTTgmEMBxRzOkzItkXxAkKsBc7jU=,tag:VBA9MLYG4bwPd+Pz4F0sNA==,type:str]
    LOKI_PASSWORD: ENC[AES256_GCM,data:DxAvXlwjSQC72wHRTlnE//+6nWHY/yv0mBnq88+IM9jSzQ68qHp+3fx3l3vtkfMFAA/7aM7+/e3eBu7QtzC6WB1/edCR0uFLKMCKzpLSYITqWSO6W+nx69pHZrYkna7K7H/BuD84xgrHEs7bZbkyNuqNgFJmNeU4s1auBfvLDLNgRJp+TBmRJX+8woduPBte6/4SMpE7U34=,iv:S5tcPSvXjEUVHhSO7cUUzQCUCWVaqVOOQ9lAHDU/+QA=,tag:f6DEg9oFVJ88KYiL6LSToQ==,type:str]
    LOKI_USERNAME: ENC[AES256_GCM,data:Tx4gFXzzEIs=,iv:9AKAZ9j+glXL2G/JAc58vbWhaOKi7V6ql3I8ex0369g=,tag:EphN66ICXvioiUH91kKtLQ==,type:str]
    PROMETHEUS_HOST: ENC[AES256_GCM,data:vEh88ALG2CjkQIwb24c7IToMWYdrrxXZTTujxSqKzngOncLBnsA6O4p69u40qRykk0tAYgh8Q7qZEKrkKUYxVg==,iv:M40JQTuoqxCMqRLWyuP6gYLdNWHoPpSnLdvBtyl9PnA=,tag:PSlgAg+ccszkQb/CXxfwmQ==,type:str]
    PROMETHEUS_PASSWORD: ENC[AES256_GCM,data:wQ8WKxlYFz4Fskuz84fmWLhrgy1AUugXvC2i4NOauEG+HRHgAkYtFlOkAdN0SKDKtzS3YmSYZPgqN6YiK3qWeSIgq6GZYsvKHqJXEZABK8dlt1AQ7hjvG5UmkMdfROAWBIikAMqgKb76m7KjzEd4s9DKH1Ck55b1T9ui42IjQCmbq/1S99jMur90kNMuqiQIa1zUewB8Dcw=,iv:Rzs6pf9+nMo9/1LWXXXWRNuk7pSvEaE7g607Nu1GByk=,tag:ZnpJdAIlROmTip4iibjSRw==,type:str]
    PROMETHEUS_USERNAME: ENC[AES256_GCM,data:j/6e6ybp//c=,iv:LOM08vSXrVTt0f+Hblcg67ylPG/y3Z+E1hWsHV3BE+A=,tag:jXgJ58w7ATGMVNl8GhBY+A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: monitoring-credentials
    namespace: monitoring
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1syptj3n067ttwafr92k4fpz4djxlpr5h39stx6ut5ex2ycsh5y4qcawr25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoNUpMZTNMaDZGWXpvN0Q2
            ZEU4OWNISHllNzZjK2dyS0VFOS9JamdWQUd3CnpRTTU2SjFNMCszY1drcm9FZVB4
            Y00zSEZhZUczUEtsbkNnTGcwb014VG8KLS0tIGZIK3pvNGg4S3U3RU1oNkpQYjZv
            OEtNYmdhRDNvTkFDVGc0cjZza2tlTE0Kf6kvDhvd7nUlgxDv9W4Cl1NKJ+D8H1uA
            mgQtEV4r7LC/0PVCLfYWfcV3Q6iLOW7RtfFWuOaazBIIRBRkmby5Qw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1hn70272w2fx9warzxjwnnsxfaa449z56nzjc6yp6y2nhc8rwf49qjsh5c2
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5N2xXeGZqOU4yS0xoMWxu
            U2QvNHpZdktKWHllSjFIYXVUeUsvUGJhN3lrCjhoSDBpWXY2ZW5BYzE1UWlHTnJ3
            ZWlLK3dEa0VoeDc0akh1L2FUdXgrdnMKLS0tIERCbDVIdXAwSUZrZEloSzhXUHVJ
            amxXUnhOR0EydkxmQzF5Y0dzNkxVeGMKt1481tpHtiHDN1S148AgL5JvURF+MeV2
            V4h9lbZI2V+dAqs7cXIlas/JyGtIPs6GKYvzxaYP8BcZnzz6m8HKtA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-06-19T18:42:04Z"
    mac: ENC[AES256_GCM,data:moUq4J/mlkIxwBTjhZoX8YUeDmFUy1/kWPUnHVyZkZmYIatW84S/ocdB2xhq4L/pRC4w0FdOMOyr7SBhX5ME6v+DSHyr3jpDrNUMM2wAXn8Q7Qc8t4pO6dJQ990sLtLRHIqcTT2HmLpTf3LjbqtzaYI28+M/1G6/pfPBaTSmRfM=,iv:o6/RVGuWqH4nekNJY7NmxIHnrvyhchq/QOHyF1TcS5k=,tag:waccLiCF15fw7tqxm7uQiw==,type:str]
    pgp: []
    encrypted_regex: ^(env|data|stringData)$
    version: 3.7.3
