apiVersion: v1
kind: Namespace
metadata:
  name: actions-runner-system
  labels:
    toolkit.fluxcd.io/tenant: dev-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: flux-system
spec:
  interval: 24h0m0s
  url: https://actions-runner-controller.github.io/actions-runner-controller
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: actions-runner-controller
  namespace: actions-runner-system
spec:
  interval: 30m
  chart:
    spec:
      chart: actions-runner-controller
      version: "0.23.*" #current: 0.23.7
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: flux-system
      interval: 12h
  values:
    metrics:
      serviceMonitor:
        enable: false
    logFormat: json
    actionsMetricsServer:
      enabled: false
    actionsMetrics:
      serviceMonitor:
        enable: false
  