apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: cloudflare
  namespace: network
spec:
  interval: 24h0m0s
  url: https://cloudflare.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflared
  namespace: network
spec:
  interval: 30m
  targetNamespace: network
  chart:
    spec:
      chart: cloudflare-tunnel
      version: "0.3.*" # current: 0.3.0 
      sourceRef:
        kind: HelmRepository
        name: cloudflare
        namespace: network
      interval: 12h
  values:
    cloudflare:
      account: ${cf_account_id}
      tunnelName: ${cf_tunnel_name}
      tunnelId: ${cf_tunnel_id}
      secretName: tunnel-credentials
      ingress: []
    replicaCount: 2
    resources: {}
      # limits:
      #   cpu: 100m
      #   memory: 128Mi
      # requests:
      #   cpu: 100m
      #   memory: 128Mi
