---
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflared
  namespace: network
spec:
  endpoints:
    - dnsName: "k8s-staging.mlan.tech"
      recordType: CNAME
      targets:
        - "${cf_tunnel_id}.cfargotunnel.com"
      providerSpecific:
        - name: external-dns.alpha.kubernetes.io/cloudflare-proxied
          value: 'true'
