apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/grafana-cloud-monitoring
  - ../base/github-ci-runner
  - ../base/capacitor
  - ../base/cloudflared
  - dns-endpoints.yaml
patches:
  - path: ingress-patch.yaml
    target:
      kind: HelmRelease
